Language = {}

Language = {
    lang_1 = 'you do not have permission for this',
    lang_2 = 'no one close enough',
    lang_3 = 'Fines',
    lang_4 = 'Fine a person',
    lang_5 = 'Create a fine',
    lang_6 = 'Register the fine in law records',
    lang_7 = 'Register fine',
    lang_8 = 'Fine description',
    lang_9 = 'Enter the description of the offense - MAX 500 characters',
    lang_10 = 'Amount',
    lang_11 = 'Amount of the fine to be applied',
    lang_12 = 'Enter the offender\'s first name',
    lang_13 = 'First Name',
    lang_14 = 'Enter the offender\'s last name',
    lang_15 = 'Last Name',
    lang_16 = 'Outstanding Fines',
    lang_17 = 'View fines that have not yet been paid',
    lang_18 = 'Defaulters',
    lang_19 = 'Fine Date:',
    lang_20 = 'Fine Issued',
    lang_21 = 'Fine Issued by:',
    lang_22 = 'Reference:',
    lang_23 = 'Description:',
    lang_24 = 'Delete fine',
    lang_25 = 'By accepting, you will permanently delete this fine. Are you sure?',
    lang_26 = 'You do not have permission for this!',
    lang_27 = 'You can only delete a fine within your jurisdiction!',
    lang_28 = 'Fine deleted!',
    lang_29 = 'Fine paid!',
    lang_30 = 'You do not have enough money!',


}
